// Anima LoRA schema - based on mikazuki/schema/anima-lora.ts

import { when, all, oneOf } from './schemaRegistry.js';

const ANIMA_TABS = [
  { key: 'model', label: '模型' },
  { key: 'dataset', label: '数据集' },
  { key: 'network', label: '网络' },
  { key: 'optimizer', label: '优化器' },
  { key: 'training', label: '训练' },
  { key: 'preview', label: '预览/验证' },
  { key: 'speed', label: '加速' },
  { key: 'advanced', label: '高级' },
];

const ANIMA_BLOCK_WEIGHTS_28 = Array(28).fill('1').join(',');
const swapEnabled = oneOf('swap_granularity', ['auto', 'block', 'merged_block', 'layer']);

const ANIMA_SECTIONS = [
  {
    id: 'model-settings',
    tab: 'model',
    title: '训练用模型',
    description: 'Anima DiT 权重、VAE、文本模型与恢复训练。',
    fields: [
      { key: 'model_train_type', type: 'hidden', defaultValue: 'anima-lora' },
      { key: 'pretrained_model_name_or_path', type: 'file', pickerType: 'model-file', label: 'Anima DiT 权重路径', desc: 'Anima 主 DiT / transformer 权重路径。', defaultValue: './sd-models/model.safetensors' },
      { key: 'vae', type: 'file', pickerType: 'model-file', label: 'Qwen Image VAE 路径', desc: 'Anima 训练必填。', defaultValue: '' },
      { key: 'qwen3', type: 'file', pickerType: 'model-file', label: 'Qwen3 文本模型路径', desc: '可填单个 safetensors 或本地模型6ee录。', defaultValue: '' },
      { key: 'llm_adapter_path', type: 'file', pickerType: 'model-file', label: 'LLM Adapter 路径', desc: '（可选）覆盖 Anima 内置 Adapter。', defaultValue: '' },
      { key: 't5_tokenizer_path', type: 'folder', pickerType: 'folder', label: 'T5 Tokenizer 目录', desc: '（可选）留空回退到 configs/t5_old。', defaultValue: '' },
      { key: 'network_weights', type: 'file', pickerType: 'output-model-file', label: '继续训练 LoRA', desc: '从已有的 LoRA 模型上继续训练，填写路径', defaultValue: '' },
      { key: 'dit_adapter_path', type: 'file', pickerType: 'output-model-file', label: 'Anima DiT Adapter', desc: '加载已有 Anima DiT adapter 权重，仅作为 adapter 权重恢复/初始化使用。', defaultValue: '' },
      { key: 'resume', type: 'folder', pickerType: 'output-folder', label: '继续训练路径', desc: '从 save_state 保存的中断状态继续训练。', defaultValue: '' },
    ],
  },
  {
    id: 'anima-params',
    tab: 'model',
    title: 'Anima 专用参数',
    description: '时间步采样、注意力实现与 VAE 设置。',
    fields: [
      { key: 'qwen3_max_token_length', type: 'number', label: 'Qwen3 最大 token 长度', defaultValue: 512, min: 1 },
      { key: 't5_max_token_length', type: 'number', label: 'T5 最大 token 长度', defaultValue: 512, min: 1 },
      { key: 'timestep_sampling', type: 'select', label: '时间步采样', desc: '默认与官方 Anima 一致的 shift。', defaultValue: 'shift', options: ['sigma', 'uniform', 'sigmoid', 'shift', 'flux_shift'] },
      { key: 'discrete_flow_shift', type: 'number', label: 'Flow Shift', desc: 'Rectified Flow 位移，默认 3.0。', defaultValue: 3.0, step: 0.001 },
      { key: 'min_timestep', type: 'number', label: '最小时间步', desc: '训练时允许的最小 timestep。', defaultValue: '', min: 0 },
      { key: 'max_timestep', type: 'number', label: '最大时间步', desc: '训练时允许的最大 timestep。', defaultValue: '', min: 1 },
      { key: 'weighting_scheme', type: 'select', label: '时间步权重策略', defaultValue: 'uniform', options: ['sigma_sqrt', 'logit_normal', 'mode', 'cosmap', 'none', 'uniform'] },
      { key: 'mode_scale', type: 'number', label: 'mode 权重缩放', desc: 'mode 权重策略的缩放系数', defaultValue: '', step: 0.01 },
      { key: 'attn_mode', type: 'select', label: 'Attention 实现', desc: 'Attention 实现。留空时按当前运行时自动选择；在 FlashAttention 运行时下，Anima 会优先尝试 FlashAttention 2。', defaultValue: '', options: ['', 'torch', 'xformers', 'sageattn', 'flash'] },
      { key: 'split_attn', type: 'boolean', label: '拆分 Attention', desc: '拆分 attention 降低显存，会牺牲速度。', defaultValue: false },
      { key: 'vae_chunk_size', type: 'number', label: 'VAE 分块大小', desc: '需为偶数。', defaultValue: '', min: 2 },
      { key: 'vae_disable_cache', type: 'boolean', label: '禁用 VAE 缓存', defaultValue: false },
      { key: 'unsloth_offload_checkpointing', type: 'boolean', label: 'Unsloth Offload', desc: '更快的 CPU RAM activation offload。', defaultValue: false },
    ],
  },
  {
    id: 'save-settings',
    tab: 'model',
    title: '保存设置',
    description: '输出路径、格式与训练状态快照。',
    fields: [
      { key: 'output_name', type: 'string', label: '模型保存名称', defaultValue: 'aki' },
      { key: 'output_dir', type: 'folder', pickerType: 'folder', label: '模型保存文件夹', defaultValue: './output' },
      { key: 'save_model_as', type: 'select', label: '保存格式', defaultValue: 'safetensors', options: ['safetensors', 'pt', 'ckpt'] },
      { key: 'save_precision', type: 'select', label: '保存精度', defaultValue: 'fp16', options: ['fp16', 'float', 'bf16'] },
      { key: 'save_every_n_epochs', type: 'number', label: '每 N 轮保存', defaultValue: 2, min: 1 },
      { key: 'save_every_n_steps', type: 'number', label: '每 N 步保存', defaultValue: '', min: 1 },
      { key: 'save_state', type: 'boolean', label: '保存训练状态', defaultValue: false },
      { key: 'save_state_on_train_end', type: 'boolean', label: '结束时额外保存状态', defaultValue: false },
      { key: 'save_last_n_epochs_state', type: 'number', label: '保留最近 N 个 epoch 状态', defaultValue: '', min: 1, visibleWhen: when('save_state', true) },
    ],
  },
  {
    id: 'dataset-settings',
    tab: 'dataset',
    title: '数据集设置',
    description: '训练数据、正则图与分桶策略。',
    fields: [
      { key: 'train_data_dir', type: 'folder', pickerType: 'folder', label: '训练数据集路径', defaultValue: './train/aki' },
      { key: 'reg_data_dir', type: 'folder', pickerType: 'folder', label: '正则化数据集路径', defaultValue: '' },
      { key: 'resolution', type: 'string', label: '训练分辨率', desc: '宽,高，必须是 64 的倍数。', defaultValue: '1024,1024' },
      { key: 'enable_bucket', type: 'boolean', label: '启用分桶', defaultValue: true },
      { key: 'min_bucket_reso', type: 'number', label: '桶最小分辨率', defaultValue: 256 },
      { key: 'max_bucket_reso', type: 'number', label: '桶最大分辨率', defaultValue: 2048 },
      { key: 'bucket_reso_steps', type: 'number', label: '桶划分单位', defaultValue: 64 },
      { key: 'bucket_no_upscale', type: 'boolean', label: '桶不放大图片', defaultValue: true },
    ],
  },
  {
    id: 'peak-vram-settings',
    tab: 'speed',
    title: '显存峰值控制',
    description: '目标等效 batch、启动峰值保护、micro-batch 拆分与显存诊断。',
    fields: [
      { key: 'peak_vram_control_enabled', type: 'boolean', label: '启用显存峰值控制', desc: '提供目标等效 batch、启动峰值保护、micro-batch 拆分与轻量显存诊断', defaultValue: false },
      { key: 'peak_vram_target_effective_batch', type: 'number', label: '目标等效 Batch', desc: '填写 0 表示关闭。填写后会自动计算并覆盖梯度累积步数（gradient_accumulation_steps），使 batch_size × 累积步数 ≈ 目标值，而不会抬高单步 batch', defaultValue: 0, min: 0, visibleWhen: v => v.peak_vram_control_enabled === true },
      { key: 'peak_vram_startup_guard_enabled', type: 'boolean', label: '启动峰值保护', desc: '训练开始前若干步套用更保守的省显存策略（推荐高 batch 开启）', defaultValue: false, visibleWhen: v => v.peak_vram_control_enabled === true },
      { key: 'peak_vram_startup_guard_mode', type: 'select', label: '保护强度', desc: 'auto 自动估计；balanced 偏平衡；aggressive 偏省显存', defaultValue: 'auto', options: ['auto', 'balanced', 'aggressive'], visibleWhen: v => v.peak_vram_control_enabled === true && v.peak_vram_startup_guard_enabled === true },
      { key: 'peak_vram_startup_guard_steps', type: 'number', label: '保护持续步数', desc: '启动峰值保护持续多少个优化 step。0 表示整段训练都保留。一般前几步最容易爆显存，不用开太大', defaultValue: 24, min: 0, visibleWhen: v => v.peak_vram_control_enabled === true && v.peak_vram_startup_guard_enabled === true },
      { key: 'peak_vram_micro_batch_enabled', type: 'boolean', label: 'Micro-Batch 拆分', desc: '把当前 batch 拆成更小的前后向子批次，降低单次峰值显存。也有助于改善大 batch 下的过拟合问题', defaultValue: false, visibleWhen: v => v.peak_vram_control_enabled === true },
      { key: 'peak_vram_micro_batch_size', type: 'number', label: 'Micro-Batch 大小', desc: '每个 micro-batch 的前后向 batch 大小', defaultValue: 1, min: 1, visibleWhen: v => v.peak_vram_control_enabled === true && v.peak_vram_micro_batch_enabled === true },
      { key: 'peak_vram_diagnostics_enabled', type: 'boolean', label: '显存诊断', desc: '训练中按设定间隔输出显存峰值', defaultValue: false, visibleWhen: v => v.peak_vram_control_enabled === true },
      { key: 'peak_vram_diagnostics_interval', type: 'number', label: '诊断间隔 (步)', desc: '每 N 个优化 step 输出一次显存诊断', defaultValue: 25, min: 1, visibleWhen: v => v.peak_vram_control_enabled === true && v.peak_vram_diagnostics_enabled === true },
      { key: 'peak_vram_auto_protection_enabled', type: 'boolean', label: '动态显存自动保护', desc: '遇到真实 OOM 时自动降一档保护并重试当前 step，稳定后逐档恢复。注意：开启后训练速度会略有下降，仅建议在显存紧张时使用', defaultValue: false, visibleWhen: v => v.peak_vram_control_enabled === true },
    ],
  },

  {
    id: 'caption-settings',
    tab: 'dataset',
    title: 'Caption（Tag）选项',
    description: 'Anima 支持 JSON 结构化标签。',
    fields: [
      { key: 'prefer_json_caption', type: 'boolean', label: '优先 JSON 标签', desc: '优先读取同名 JSON 标签文件；若不存在回退 TXT。', defaultValue: true },
      { key: 'caption_extension', type: 'string', label: 'Tag 文件扩展名', defaultValue: '.txt' },
      { key: 'shuffle_caption', type: 'boolean', label: '随机打乱标签', desc: 'JSON 模式下分组打乱。', defaultValue: false },
      { key: 'keep_tokens', type: 'number', label: '保留前 N 个 token', defaultValue: 0, min: 0, max: 255 },
      { key: 'caption_tag_dropout_rate', type: 'number', label: '标签丢弃概率', defaultValue: '', min: 0, step: 0.01 },
    ],
  },
  {
    id: 'network-settings',
    tab: 'network',
    title: '网络设置',
    description: 'LoRA / T-LoRA / LoKr / GLoKr 适配器参数。',
    fields: [
      { key: 'lora_type', type: 'select', label: '适配器类型', desc: 'LoRA 是基础路线；LoRA-FA 冻结 lora_down；VeRA 使用共享随机投影；T-LoRA 动态 rank；LoKr 为实验路线；GLoKr 走 Anima 的 LyCORIS 混合路线。', defaultValue: 'lora', options: ['lora', 'dora', 'lora_fa', 'vera', 'tlora', 'hydralora', 'fera', 'loha', 'locon', 'lokr', 'glokr'] },
      { key: 'network_dim', type: 'slider', label: '网络维度', defaultValue: 16, min: 1, max: 512, step: 1 },
      { key: 'network_alpha', type: 'slider', label: '网络 Alpha', defaultValue: 16, min: 1, max: 512, step: 1 },
      { key: 'dim_from_weights', type: 'boolean', label: '从权重推断 Dim', defaultValue: false },
      { key: 'scale_weight_norms', type: 'number', label: '最大范数正则化', defaultValue: '', min: 0, step: 0.01 },
      { key: 'train_norm', type: 'boolean', label: '训练 Norm 层', desc: '额外训练带可学习参数的归一化层（如 RMSNorm/LayerNorm 的 weight/bias），用于微调特征尺度和风格/域适配；会小幅增加显存占用和 LoRA 文件大小，并增加过拟合风险，普通训练建议先关闭。', defaultValue: false },
      { key: 'network_dropout', type: 'number', label: 'Dropout', defaultValue: 0, min: 0, step: 0.01, visibleWhen: (c) => c.lora_type === 'lora' || c.lora_type === 'lora_fa' || c.lora_type === 'vera' || c.lora_type === 'tlora' || c.lora_type === 'lokr' },
      { key: 'dropout', type: 'number', label: 'GLoKr Dropout', desc: 'GLoKr 主 dropout 概率。', defaultValue: 0, min: 0, max: 1, step: 0.01, visibleWhen: when('lora_type', 'glokr') },
      { key: 'rank_dropout', type: 'number', label: 'GLoKr Rank Dropout', desc: 'GLoKr rank dropout 概率。', defaultValue: '', min: 0, max: 1, step: 0.01, visibleWhen: when('lora_type', 'glokr') },
      { key: 'module_dropout', type: 'number', label: 'GLoKr Module Dropout', desc: 'GLoKr module dropout 概率。', defaultValue: '', min: 0, max: 1, step: 0.01, visibleWhen: when('lora_type', 'glokr') },
      { key: 'use_scalar', type: 'boolean', label: 'GLoKr Scalar 参数化', desc: '启用 GLoKr 的 scalar 参数化。', defaultValue: false, visibleWhen: when('lora_type', 'glokr') },
      { key: 'rs_lora', type: 'boolean', label: 'GLoKr rsLoRA 缩放', desc: '启用 GLoKr 的 rsLoRA 风格缩放。', defaultValue: false, visibleWhen: when('lora_type', 'glokr') },
      { key: 'dora_wd', type: 'boolean', label: 'GLoKr DoRA', desc: '在 GLoKr 路线下启用 DoRA。', defaultValue: false, visibleWhen: when('lora_type', 'glokr') },
      { key: 'wd_on_output', type: 'boolean', label: 'GLoKr DoRA 输出侧范数', desc: 'GLoKr DoRA 范数统计沿输出通道计算。', defaultValue: true, visibleWhen: when('lora_type', 'glokr') },
      { key: 'bypass_mode', type: 'boolean', label: 'GLoKr Bypass Mode', desc: 'LyCORIS 兼容字段。启用 DoRA 时一般建议关闭。', defaultValue: false, visibleWhen: when('lora_type', 'glokr') },
      { key: 'tlora_min_rank', type: 'number', label: 'T-LoRA 最小 Rank', defaultValue: 1, min: 1, visibleWhen: when('lora_type', 'tlora') },
      { key: 'tlora_rank_schedule', type: 'select', label: 'T-LoRA Rank 调度', defaultValue: 'linear', options: ['constant', 'linear', 'geometric'], visibleWhen: when('lora_type', 'tlora') },
      { key: 'pissa_init', type: 'boolean', label: '启用 PiSSA 初始化', defaultValue: false, visibleWhen: when('lora_type', 'lora') },
      { key: 'lokr_factor', type: 'number', label: 'LoKr / GLoKr 分解因子', defaultValue: -1, min: -1, visibleWhen: (c) => c.lora_type === 'lokr' || c.lora_type === 'glokr' },
      { key: 'lokr_rank_dropout', type: 'number', label: 'LoKr Rank Dropout', defaultValue: 0, min: 0, max: 1, step: 0.01, visibleWhen: when('lora_type', 'lokr') },
      { key: 'lokr_module_dropout', type: 'number', label: 'LoKr Module Dropout', defaultValue: 0, min: 0, max: 1, step: 0.01, visibleWhen: when('lora_type', 'lokr') },
      { key: 'lokr_train_norm', type: 'boolean', label: 'LoKr 训练 Norm', desc: '启用后 LoKr 会额外注入 LayerNorm/RMSNorm 适配参数。', defaultValue: false, visibleWhen: when('lora_type', 'lokr') },
      { key: 'lokr_export_mode', type: 'select', label: 'LoKr 保存格式', desc: 'native 保留原生 LoKr 权重；lora_compatible 会展开为标准 LoRA 兼容权重。', defaultValue: 'native', options: ['native', 'lora_compatible'], visibleWhen: when('lora_type', 'lokr') },
      { key: 'full_matrix', type: 'boolean', label: 'LoKr / GLoKr Full Matrix', desc: '强制使用 direct lokr_w1/lokr_w2 分支。', defaultValue: false, visibleWhen: (c) => c.lora_type === 'lokr' || c.lora_type === 'glokr' },
      { key: 'decompose_both', type: 'boolean', label: 'LoKr / GLoKr 双侧分解', desc: '启用 lokr_w1_a/b 和 lokr_w2_a/b 低秩分支。', defaultValue: false, visibleWhen: (c) => c.lora_type === 'lokr' || c.lora_type === 'glokr' },
      { key: 'unbalanced_factorization', type: 'boolean', label: 'LoKr / GLoKr 非均衡分解', desc: '交换输出分解维度，用于对齐 LyCORIS 实验语义。', defaultValue: false, visibleWhen: (c) => c.lora_type === 'lokr' || c.lora_type === 'glokr' },
      { key: 'hydralora_num_experts', type: 'number', label: 'HydraLoRA 专家数', defaultValue: 4, min: 1, visibleWhen: when('lora_type', 'hydralora') },
      { key: 'hydralora_routing', type: 'select', label: 'HydraLoRA 路由', defaultValue: 'top_k', options: ['top_k', 'dense'], visibleWhen: when('lora_type', 'hydralora') },
      { key: 'hydralora_top_k', type: 'number', label: 'HydraLoRA Top-K', defaultValue: 2, min: 1, visibleWhen: when('lora_type', 'hydralora') },
      { key: 'hydralora_balance_loss_weight', type: 'number', label: 'HydraLoRA 均衡 Loss 权重', defaultValue: 0, min: 0, step: 0.001, visibleWhen: when('lora_type', 'hydralora') },
      { key: 'fera_gate_init', type: 'number', label: 'FeRA Gate 初始值', defaultValue: 0, step: 0.001, visibleWhen: when('lora_type', 'fera') },
      { key: 'easy_control_enabled', type: 'boolean', label: '启用 EasyControl', desc: '接收 batch 中的 control_images 并在 noisy latent 前加入轻量 residual；完整 sidecar 数据集接线仍需后续闭环。', defaultValue: false },
      { key: 'control_image_dir', type: 'directory', label: 'Control 图片目录', defaultValue: '', visibleWhen: when('easy_control_enabled', true) },
      { key: 'control_suffix', type: 'string', label: 'Control 文件后缀', defaultValue: '', visibleWhen: when('easy_control_enabled', true) },
      { key: 'easy_control_scale', type: 'number', label: 'EasyControl Scale', defaultValue: 1, min: 0, step: 0.01, visibleWhen: when('easy_control_enabled', true) },
      { key: 'easy_control_channels', type: 'number', label: 'EasyControl 通道数', defaultValue: 3, min: 1, visibleWhen: when('easy_control_enabled', true) },
      { key: 'ip_adapter_enabled', type: 'boolean', label: '启用 IP-Adapter', desc: '训练 projector 并支持 batch 中的 ip_adapter_image_features；真实图像编码器接线仍需后续闭环。', defaultValue: false },
      { key: 'ip_adapter_encoder_dim', type: 'number', label: 'IP-Adapter Encoder Dim', defaultValue: 1024, min: 1, visibleWhen: when('ip_adapter_enabled', true) },
      { key: 'ip_adapter_cond_dim', type: 'number', label: 'IP-Adapter Cond Dim', defaultValue: 1152, min: 1, visibleWhen: when('ip_adapter_enabled', true) },
      { key: 'ip_adapter_num_image_tokens', type: 'number', label: 'IP-Adapter Image Tokens', defaultValue: 16, min: 1, visibleWhen: when('ip_adapter_enabled', true) },
      { key: 'ip_adapter_scale', type: 'number', label: 'IP-Adapter Scale', defaultValue: 1, min: 0, step: 0.01, visibleWhen: when('ip_adapter_enabled', true) },
      { key: 'ip_adapter_cond_mode', type: 'select', label: 'IP-Adapter Cond 模式', defaultValue: 'concat', options: ['concat', 'replace'], visibleWhen: when('ip_adapter_enabled', true) },
      { key: 'reft_enabled', type: 'boolean', label: '启用 ReFT', desc: '在指定 DiT 模块 hidden state 上训练低秩 residual intervention。', defaultValue: false },
      { key: 'reft_target_modules', type: 'textarea', label: 'ReFT 目标模块', desc: '逗号/换行分隔的模块路径，例如 net.blocks.0 或 blocks.0。', defaultValue: '', visibleWhen: when('reft_enabled', true) },
      { key: 'reft_rank', type: 'number', label: 'ReFT Rank', defaultValue: 8, min: 1, visibleWhen: when('reft_enabled', true) },
      { key: 'reft_init_scale', type: 'number', label: 'ReFT 初始尺度', defaultValue: 0, min: 0, step: 0.001, visibleWhen: when('reft_enabled', true) },
      { key: 'enable_base_weight', type: 'boolean', label: '启用基础权重', defaultValue: false },
    ],
  },
  {
    id: 'optimizer-settings',
    tab: 'optimizer',
    title: '学习率与优化器',
    description: '学习率、调度器与优化器类型。',
    fields: [
      { key: 'learning_rate', type: 'string', label: '总学习率', defaultValue: '1e-4' },
      { key: 'unet_lr', type: 'string', label: 'DiT 学习率', defaultValue: '1e-4' },
      { key: 'text_encoder_lr', type: 'string', label: '文本编码器学习率', defaultValue: '1e-5' },
      { key: 'weight_decay', type: 'number', label: '权重衰减', desc: '权重衰减（等价于自动注入 optimizer_args: weight_decay=...）', defaultValue: '', step: 0.0001 },
      { key: 'lr_scheduler', type: 'select', label: '学习率调度器', defaultValue: 'cosine_with_restarts', options: ['linear', 'cosine', 'cosine_with_restarts', 'polynomial', 'constant', 'constant_with_warmup'] },
      { key: 'lr_warmup_steps', type: 'number', label: '预热步数', defaultValue: 0, min: 0 },
      { key: 'lr_scheduler_num_cycles', type: 'number', label: '重启次数', defaultValue: 1, min: 1, visibleWhen: when('lr_scheduler', 'cosine_with_restarts') },
      { key: 'optimizer_type', type: 'select', label: '优化器', defaultValue: 'AdamW8bit', options: ['AdamW', 'AdamW8bit', 'AdamW8bitKahan', 'PagedAdamW8bit', 'Lion', 'Lion8bit', 'DAdaptation', 'DAdaptAdam', 'DAdaptLion', 'AdaFactor', 'Prodigy', 'pytorch_optimizer.CAME', 'pytorch_optimizer.Compass', 'pytorch_optimizer.Ranger21', 'pytorch_optimizer.AdEMAMix'] },
      { key: 'min_snr_gamma', type: 'number', label: 'Min-SNR Gamma', defaultValue: '', min: 0, step: 0.1 },
    ],
  },
  {
    id: 'training-settings',
    tab: 'training',
    title: '训练相关参数',
    description: '基础训练轮数、批量与反向传播。',
    fields: [
      { key: 'max_train_epochs', type: 'number', label: '最大训练轮数', defaultValue: 10, min: 1 },
      { key: 'train_batch_size', type: 'slider', label: '批量大小', defaultValue: 1, min: 1, max: 32, step: 1 },
      { key: 'gradient_checkpointing', type: 'boolean', label: '梯度检查点', defaultValue: true },
      { key: 'gradient_accumulation_steps', type: 'number', label: '梯度累加步数', defaultValue: 1, min: 1 },
      { key: 'network_train_unet_only', type: 'boolean', label: '仅训练 DiT', desc: '仅训练 DiT / U-Net。', defaultValue: true },
      { key: 'network_train_text_encoder_only', type: 'boolean', label: '仅训练文本编码器', defaultValue: false },
    ],
  },
  {
    id: 'staged-resolution-settings',
    tab: 'training',
    title: '阶段分辨率训练',
    description: '实验性，支持 Anima。1024 基准使用 512/768/1024；2048 基准使用 1024/1536/2048。',
    fields: [
      { key: 'enable_mixed_resolution_training', type: 'boolean', label: '启用阶段分辨率训练', defaultValue: false },
      { key: 'staged_resolution_ratio_512', type: 'number', label: '512 阶段占比 (%)', desc: '当最终分辨率最大边 < 512 时忽略', defaultValue: 20, min: 0, max: 100, step: 1, visibleWhen: when('enable_mixed_resolution_training', true) },
      { key: 'staged_resolution_ratio_768', type: 'number', label: '768 阶段占比 (%)', desc: '当最终分辨率最大边 < 768 时忽略', defaultValue: 30, min: 0, max: 100, step: 1, visibleWhen: when('enable_mixed_resolution_training', true) },
      { key: 'staged_resolution_ratio_1024', type: 'number', label: '1024 阶段占比 (%)', desc: '1024 基准和 2048 基准都会用到', defaultValue: 50, min: 0, max: 100, step: 1, visibleWhen: when('enable_mixed_resolution_training', true) },
      { key: 'staged_resolution_ratio_1536', type: 'number', label: '1536 阶段占比 (%)', desc: '仅 2048 基准会用到', defaultValue: 30, min: 0, max: 100, step: 1, visibleWhen: when('enable_mixed_resolution_training', true) },
      { key: 'staged_resolution_ratio_2048', type: 'number', label: '2048 阶段占比 (%)', desc: '仅 2048 基准会用到', defaultValue: 50, min: 0, max: 100, step: 1, visibleWhen: when('enable_mixed_resolution_training', true) },
    ],
  },
  {
    id: 'preview-settings',
    tab: 'preview',
    title: '训练预览图',
    description: 'Anima 训练中生成预览图的配置。',
    fields: [
      { key: 'enable_preview', type: 'boolean', label: '启用预览图', defaultValue: false },
      { key: 'positive_prompts', type: 'textarea', label: '正向提示词', defaultValue: 'newest, safe, 1girl, masterpiece, best quality', visibleWhen: when('enable_preview', true) },
      { key: 'negative_prompts', type: 'textarea', label: '反向提示词', defaultValue: '', visibleWhen: when('enable_preview', true) },
      { key: 'sample_width', type: 'number', label: '预览图宽', defaultValue: 1024, min: 64, visibleWhen: when('enable_preview', true) },
      { key: 'sample_height', type: 'number', label: '预览图高', defaultValue: 1024, min: 64, visibleWhen: when('enable_preview', true) },
      { key: 'sample_cfg', type: 'number', label: 'CFG', defaultValue: 4, min: 1, max: 30, visibleWhen: when('enable_preview', true) },
      { key: 'sample_steps', type: 'number', label: '推理步数', defaultValue: 25, min: 1, max: 300, visibleWhen: when('enable_preview', true) },
      { key: 'sample_sampler', type: 'select', label: '采样器', desc: '预览采样器。当前 Anima 训练预览只支持 euler / k_euler；导入旧配置时会自动把不兼容值规范化', defaultValue: 'euler', options: ['euler', 'k_euler'], visibleWhen: when('enable_preview', true) },
      { key: 'sample_scheduler', type: 'select', label: '预览调度器', desc: 'Anima 预览调度器。当前训练预览支持 simple', defaultValue: 'simple', options: ['simple'], visibleWhen: when('enable_preview', true) },
      { key: 'sample_every_n_epochs', type: 'number', label: '每 N 个 epoch 生成', defaultValue: 2, min: 1, visibleWhen: when('enable_preview', true) },
      { key: 'sample_at_first', type: 'boolean', label: '训练前先生成', defaultValue: false, visibleWhen: when('enable_preview', true) },
      { key: 'validation_split', type: 'number', label: '验证集划分比例', defaultValue: 0, min: 0, max: 1, step: 0.01 },
      { key: 'log_with', type: 'select', label: '日志模块', defaultValue: 'tensorboard', options: ['tensorboard', 'wandb'] },
      { key: 'logging_dir', type: 'folder', pickerType: 'folder', label: '日志保存文件夹', defaultValue: './logs' },
    ],
  },
  {
    id: 'speed-settings',
    tab: 'speed',
    title: '速度优化选项',
    description: '混合精度、缓存与 FP8。',
    fields: [
      { key: 'mixed_precision', type: 'select', label: '混合精度', defaultValue: 'bf16', options: ['no', 'fp16', 'bf16'] },
      { key: 'fp8_base', type: 'boolean', label: 'FP8 基础模型', defaultValue: false },
      { key: 'fp8_base_unet', type: 'boolean', label: 'FP8 仅 DiT', defaultValue: false },
      { key: 'flashattn', type: 'boolean', label: '启用 FlashAttention 2', desc: '启用 FlashAttention 2（实验性，需要 FlashAttention 运行时）', defaultValue: false },
      { key: 'lowram', type: 'boolean', label: '低内存模式', defaultValue: false },
      { key: 'cache_latents', type: 'boolean', label: '缓存 Latent', defaultValue: true },
      { key: 'cache_latents_to_disk', type: 'boolean', label: '缓存 Latent 到磁盘', defaultValue: true },
      { key: 'latent_cache_disk_format', type: 'select', label: 'Latent 缓存格式', desc: 'latent 磁盘缓存格式。默认 safetensors；若已有旧缓存会自动兼容读取 npz', defaultValue: 'safetensors', options: ['safetensors', 'npz'] },
      { key: 'latent_cache_disk_dtype', type: 'select', label: 'Latent 缓存精度', desc: 'latent 磁盘缓存保存精度。auto 会尽量保留运行时 dtype；fp16 更省空间，fp32 兼容性更高。若选择 npz + bf16，后端会自动回退为 fp32', defaultValue: 'auto', options: ['auto', 'fp16', 'bf16', 'fp32'], visibleWhen: v => v.cache_latents_to_disk === true },
      { key: 'cache_text_encoder_outputs', type: 'boolean', label: '缓存文本编码器输出', defaultValue: true },
      { key: 'cache_text_encoder_outputs_to_disk', type: 'boolean', label: '缓存文本编码器输出到磁盘', defaultValue: true },
      { key: 'text_encoder_outputs_cache_disk_format', type: 'select', label: '文本缓存格式', desc: '文本编码器输出磁盘缓存格式。默认 safetensors；若已有旧的 npz 缓存也会自动兼容读取', defaultValue: 'safetensors', options: ['safetensors', 'npz'], visibleWhen: v => v.cache_text_encoder_outputs_to_disk === true },
      { key: 'text_encoder_outputs_cache_dtype', type: 'select', label: '文本缓存精度', desc: '文本编码器输出磁盘缓存的保存精度。auto 会尽量保留运行时 dtype；fp16 / bf16 更省空间，fp32 兼容性更高', defaultValue: 'auto', options: ['auto', 'fp16', 'bf16', 'fp32'], visibleWhen: v => v.cache_text_encoder_outputs_to_disk === true },
      { key: 'text_encoder_batch_size', type: 'number', label: '文本编码器批量大小', defaultValue: '', min: 1 },
      { key: 'swap_granularity', type: 'select', label: '显存交换模式', desc: 'off 关闭；auto 自动选择；block 按 block 搬运；merged_block 合并 block 降低 PCIe 传输次数；layer 为 Fine-grained / Layer Swap（现有细粒度 swap，不是真模块级 offload）。', defaultValue: 'off', options: ['off', 'auto', 'block', 'merged_block', 'layer'] },
      { key: 'swap_ratio', type: 'slider', label: '显存交换比例', desc: '按原始 block/layer 总数计算交换比例。0 表示只在 auto 或 swap_count 下生效。', defaultValue: 0, min: 0, max: 1, step: 0.05, visibleWhen: swapEnabled },
      { key: 'swap_count', type: 'number', label: '显存交换数量', desc: '高级：绝对交换数量。大于 0 时优先于比例。', defaultValue: 0, min: 0, visibleWhen: swapEnabled },
      { key: 'block_merge_size', type: 'number', label: '合并 Block 大小', desc: 'merged_block 模式下每组包含的 block 数。', defaultValue: 2, min: 2, visibleWhen: when('swap_granularity', 'merged_block') },
      { key: 'module_offload_enabled', type: 'boolean', label: '模块级 Offload', desc: 'clean-room 新路线：按比例让冻结的 Linear / Conv 模块常驻 CPU，训练时按需临时回到 GPU。与现有 swap 互斥。', defaultValue: false },
      { key: 'module_offload_ratio', type: 'number', label: '模块 Offload 比例', desc: '0-100，表示参与 offload 的可管理模块占比，不是目标显存占比。', defaultValue: 0, min: 0, max: 100, visibleWhen: when('module_offload_enabled', true) },
      { key: 'module_offload_backbone_ratio', type: 'number', label: '主干覆盖比例', desc: '可选 0-100；留空则继承总比例。backbone 指 UNet 或 DiT 主干。', defaultValue: '', min: 0, max: 100, visibleWhen: when('module_offload_enabled', true) },
      { key: 'module_offload_text_encoder_ratio', type: 'number', label: '文本编码器覆盖比例', desc: '可选 0-100；留空则继承总比例，并对每个启用的文本编码器独立生效。', defaultValue: '', min: 0, max: 100, visibleWhen: when('module_offload_enabled', true) },
      { key: 'blocks_to_swap', type: 'number', label: '旧版 Block 交换数量', desc: '兼容旧配置。新配置建议使用上方显存交换模式、比例和数量。', defaultValue: '', min: 1 },
      { key: 'experimental_attention_profile_enabled', type: 'boolean', label: '步骤耗时统计', desc: '步骤耗时窗口统计开关。默认关闭，仅在诊断训练速度/瓶颈时建议开启', defaultValue: false },
      { key: 'experimental_attention_profile_window', type: 'number', label: '统计窗口 (步)', desc: '每 N 个优化步输出一次聚合耗时摘要', defaultValue: 50, min: 1, visibleWhen: v => v.experimental_attention_profile_enabled === true },
      { key: 'vram_swap_to_ram', type: 'boolean', label: 'VRAM Swap to RAM', desc: '实验性：让原生 Anima LoRA / LoRA-FA / VeRA / T-LoRA 适配器权重常驻 CPU RAM，前向时再按需拉回训练设备。更省显存，但通常更慢；暂不支持 LoKr、多进程、full_fp16/full_bf16 以及部分 8bit/paged 优化器', defaultValue: false },
      { key: 'cpu_offload_checkpointing', type: 'boolean', label: 'CPU Offload 梯度检查点', defaultValue: false },
      { key: 'disable_mmap_load_safetensors', type: 'boolean', label: '禁用 mmap 加载', defaultValue: false },
      { key: 'pytorch_cuda_expandable_segments', type: 'boolean', label: '显存碎片优化', desc: '训练前自动设置 PYTORCH_ALLOC_CONF=expandable_segments:True，缓解显存碎片导致的 OOM', defaultValue: true },
    ],
  },
  {
    id: 'lulynx-experimental-core',
    tab: 'advanced',
    title: 'Lulynx 实验核心',
    description: 'SafeGuard、EMA、ResourceManager、BlockWeight (Anima 28层)、SmartRank、AutoController。',
    fields: [
      { key: 'lulynx_experimental_core_enabled', type: 'boolean', label: '启用 Lulynx 实验核心', desc: '集中管理 SafeGuard、EMA、ResourceManager、BlockWeight、SmartRank、AutoController、LISA、PCGrad、Pause、Prodigy Guard 与轻量监控', defaultValue: false },
      { key: 'lulynx_safeguard_enabled', type: 'boolean', label: '启用 SafeGuard', desc: '桥接到当前训练器的轻量安全防护，可拦截 NaN/Inf loss 与异常 spike', defaultValue: false, visibleWhen: when('lulynx_experimental_core_enabled', true) },
      { key: 'lulynx_safeguard_nan_check_interval', type: 'number', label: 'NaN 检查间隔', desc: '每 N 个优化 step 检查一次 NaN / Inf loss', defaultValue: 1, min: 1, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_safeguard_enabled', true)) },
      { key: 'lulynx_safeguard_max_nan_count', type: 'number', label: '最大连续 NaN', desc: '连续触发多少次 NaN / Inf 后直接停止训练', defaultValue: 3, min: 1, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_safeguard_enabled', true)) },
      { key: 'lulynx_safeguard_loss_spike_threshold', type: 'number', label: 'Loss Spike 阈值', desc: '当前 loss 超过滚动平均值多少倍时判定为 spike', defaultValue: 5.0, min: 1, step: 0.1, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_safeguard_enabled', true)) },
      { key: 'lulynx_safeguard_loss_window_size', type: 'number', label: 'Loss 窗口大小', desc: '判定 loss spike 的滚动窗口大小', defaultValue: 20, min: 2, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_safeguard_enabled', true)) },
      { key: 'lulynx_safeguard_auto_reduce_lr', type: 'boolean', label: '自动降学习率', desc: 'SafeGuard 触发时自动降低学习率', defaultValue: false, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_safeguard_enabled', true)) },
      { key: 'lulynx_safeguard_lr_reduction_factor', type: 'number', label: '降学习率倍率', desc: '自动降低学习率时使用的倍率', defaultValue: 0.5, min: 0.01, max: 1, step: 0.01, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_safeguard_enabled', true), when('lulynx_safeguard_auto_reduce_lr', true)) },
      { key: 'lulynx_ema_enabled', type: 'boolean', label: '启用 EMA', desc: '桥接到当前训练器的 EMA 实现，对训练参数做指数滑动平均', defaultValue: false, visibleWhen: when('lulynx_experimental_core_enabled', true) },
      { key: 'lulynx_ema_decay', type: 'number', label: 'EMA 衰减率', desc: '越接近 1 越平滑，常用 0.999~0.9999', defaultValue: 0.999, min: 0, max: 0.99999, step: 0.0001, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_ema_enabled', true)) },
      { key: 'lulynx_resource_manager_enabled', type: 'boolean', label: '启用 ResourceManager', desc: '监控显存占用并按设定节奏清理缓存，防止显存碎片累积', defaultValue: false, visibleWhen: when('lulynx_experimental_core_enabled', true) },
      { key: 'lulynx_resource_log_interval', type: 'number', label: '资源日志间隔', desc: '每 N 个优化 step 输出一次资源日志', defaultValue: 25, min: 1, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_resource_manager_enabled', true)) },
      { key: 'lulynx_block_weight_enabled', type: 'boolean', label: '启用 BlockWeight (28层)', desc: '按 Anima 主 transformer 28 层结构分配分层学习率', defaultValue: false, visibleWhen: when('lulynx_experimental_core_enabled', true) },
      { key: 'lulynx_anima_block_lr_weights', type: 'textarea', label: 'Anima 分层权重', desc: '共 28 层，blocks.0~blocks.27。设为 0 可冻结该层', defaultValue: ANIMA_BLOCK_WEIGHTS_28, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_block_weight_enabled', true)) },
      { key: 'lulynx_anima_llm_adapter_lr_weight', type: 'number', label: 'LLM Adapter 学习率倍率', desc: 'LLM Adapter 模块的学习率倍率', defaultValue: 1.0, step: 0.01, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_block_weight_enabled', true)) },
      { key: 'lulynx_anima_final_layer_lr_weight', type: 'number', label: 'final_layer 学习率倍率', desc: 'final_layer 模块的学习率倍率', defaultValue: 1.0, step: 0.01, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_block_weight_enabled', true)) },
      { key: 'lulynx_anima_norm_lr_weight', type: 'number', label: 'Norm 层学习率倍率', desc: '匹配 norm 层的学习率倍率', defaultValue: 1.0, step: 0.01, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_block_weight_enabled', true)) },
      { key: 'lulynx_smart_rank_enabled', type: 'boolean', label: '启用 SmartRank', desc: '周期性压缩低能量 rank 通道，减少冗余参数', defaultValue: false, visibleWhen: when('lulynx_experimental_core_enabled', true) },
      { key: 'lulynx_smart_rank_keep_ratio', type: 'number', label: '保留 Rank 比例', desc: '保留多少比例的 rank 通道。例如 0.75 表示裁掉最弱的 25%', defaultValue: 0.75, min: 0.05, max: 1, step: 0.01, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_smart_rank_enabled', true)) },
      { key: 'lulynx_auto_controller_enabled', type: 'boolean', label: '启用 AutoController', desc: '根据 loss 平台自动控速、降学习率或提前停止训练', defaultValue: false, visibleWhen: when('lulynx_experimental_core_enabled', true) },
      { key: 'lulynx_auto_check_every', type: 'number', label: '自动判断间隔', desc: '每 N 个优化 step 做一次 AutoController 判断', defaultValue: 50, min: 1, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_auto_controller_enabled', true)) },
      { key: 'lulynx_auto_early_stop_patience', type: 'number', label: '提前停止耐心值', desc: '连续多少次平台期后提前停止训练。数值越大越不容易提前停', defaultValue: 6, min: 1, visibleWhen: all(when('lulynx_experimental_core_enabled', true), when('lulynx_auto_controller_enabled', true)) },
    ],
  },
  {
    id: 'advanced-settings',
    tab: 'advanced',
    title: '其他设置',
    description: '噪声、随机种子与实验功能。',
    fields: [
      { key: 'noise_offset', type: 'number', label: '噪声偏移', defaultValue: '', step: 0.01 },
      { key: 'seed', type: 'number', label: '随机种子', defaultValue: 1337 },
      { key: 'masked_loss', type: 'boolean', label: '启用蓬版损失', defaultValue: false },
      { key: 'alpha_mask', type: 'boolean', label: '读取 Alpha 通道作 Mask', defaultValue: false },
      { key: 'wavelet_loss_enabled', type: 'boolean', label: '启用 Wavelet Loss', desc: '实验性：叠加多尺度 wavelet 细节损失', defaultValue: false },
      { key: 'wavelet_loss_weight', type: 'number', label: 'Wavelet Loss 权重', defaultValue: 0.05, min: 0, step: 0.01, visibleWhen: when('wavelet_loss_enabled', true) },
      { key: 'wavelet_loss_levels', type: 'number', label: 'Wavelet 层数', defaultValue: 1, min: 1, max: 4, step: 1, visibleWhen: when('wavelet_loss_enabled', true) },
      { key: 'wavelet_loss_approx_weight', type: 'number', label: 'Wavelet 低频权重', defaultValue: 0, min: 0, step: 0.01, visibleWhen: when('wavelet_loss_enabled', true) },
      { key: 'training_comment', type: 'textarea', label: '训练备注', defaultValue: '' },
      { key: 'ui_custom_params', type: 'textarea', label: '自定义 TOML 覆盖', desc: '危险：直接覆盖界面参数。', defaultValue: '' },
    ],
  },
  {
    id: 'distributed-settings',
    tab: 'advanced',
    title: '分布式训练',
    description: '多 GPU / 多机分布式训练配置。',
    fields: [
      { key: 'enable_distributed_training', type: 'boolean', label: '启用分布式训练', desc: '启用分布式启动', defaultValue: false },
      { key: 'num_processes', type: 'number', label: '进程数', desc: '每台机器启动的训练进程数', defaultValue: '', min: 1, visibleWhen: when('enable_distributed_training', true) },
      { key: 'num_machines', type: 'number', label: '机器数', defaultValue: 1, min: 1, visibleWhen: when('enable_distributed_training', true) },
      { key: 'machine_rank', type: 'number', label: '当前机器编号', defaultValue: 0, min: 0, visibleWhen: when('enable_distributed_training', true) },
      { key: 'main_process_ip', type: 'string', label: '主节点 IP', defaultValue: '', visibleWhen: when('enable_distributed_training', true) },
      { key: 'main_process_port', type: 'number', label: '主节点端口', defaultValue: 29500, min: 1, max: 65535, visibleWhen: when('enable_distributed_training', true) },
      { key: 'nccl_socket_ifname', type: 'string', label: 'NCCL 网卡名', defaultValue: '', visibleWhen: when('enable_distributed_training', true) },
      { key: 'gloo_socket_ifname', type: 'string', label: 'Gloo 网卡名', defaultValue: '', visibleWhen: when('enable_distributed_training', true) },
      { key: 'sync_config_from_main', type: 'boolean', label: '从主节点同步配置', defaultValue: true, visibleWhen: when('enable_distributed_training', true) },
      { key: 'sync_missing_assets_from_main', type: 'boolean', label: '从主节点补齐资源', defaultValue: true, visibleWhen: when('enable_distributed_training', true) },
      { key: 'clear_dataset_npz_before_train', type: 'boolean', label: '训练前清除缓存', defaultValue: false, visibleWhen: when('enable_distributed_training', true) },
      { key: 'ddp_timeout', type: 'number', label: 'DDP 超时', defaultValue: '', min: 0, visibleWhen: when('enable_distributed_training', true) },
      { key: 'ddp_static_graph', type: 'boolean', label: 'DDP Static Graph', defaultValue: false, visibleWhen: when('enable_distributed_training', true) },
    ],
  },
];

const ANIMA_CONDITIONAL_KEYS = new Set([
  'lora_type', 'enable_preview', 'save_state', 'prefer_json_caption',
  'lr_scheduler', 'optimizer_type',
  'lulynx_experimental_core_enabled', 'lulynx_safeguard_enabled',
  'lulynx_ema_enabled', 'lulynx_resource_manager_enabled',
  'lulynx_block_weight_enabled', 'lulynx_smart_rank_enabled',
  'lulynx_auto_controller_enabled', 'lulynx_safeguard_auto_reduce_lr',
  'enable_distributed_training', 'wavelet_loss_enabled',
]);

export const ANIMA_LORA_SCHEMA = {
  key: 'anima-lora',
  label: 'Anima LoRA',
  trainType: 'anima-lora',
  tabs: ANIMA_TABS,
  sections: ANIMA_SECTIONS,
  conditionalKeys: ANIMA_CONDITIONAL_KEYS,
};
