const entries = [
 {
 id: 'lab-distiller',
 label: 'LAB Distiller',
 group: 'distillation',
 source: 'lulynx',
 routeId: 'lab-distiller',
 guideEntryKey: 'lab_distiller',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: true,
 visibleTrainingToggleAllowed: true,
 reason: 'Existing experimental distillation route with UI schema and launch API.',
 },
 {
 id: 'sdxl-turbo-lora',
 label: 'SDXL Turbo / LCM LoRA',
 group: 'distillation',
 source: 'lulynx',
 routeId: 'sdxl-turbo-lora',
 guideEntryKey: 'sdxl_turbo_lora',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: true,
 visibleTrainingToggleAllowed: true,
 reason: 'Existing guarded experimental route, separate from Anima DP-DMD.',
 },
 {
 id: 'anima-few-step-lora',
 label: 'Anima Few-step LoRA',
 group: 'distillation',
 source: 'lulynx',
 routeId: 'anima-few-step-lora',
 guideEntryKey: 'anima_few_step_lora',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: true,
 visibleTrainingToggleAllowed: true,
 reason: 'Existing metadata/contract route for Anima few-step work.',
 },
 {
 id: 'newbie-few-step-lora',
 label: 'Newbie Few-step LoRA',
 group: 'distillation',
 source: 'lulynx',
 routeId: 'newbie-few-step-lora',
 guideEntryKey: 'newbie_few_step_lora',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: true,
 visibleTrainingToggleAllowed: true,
 reason: 'Existing metadata/contract route for Newbie few-step work.',
 },
 {
 id: 'cns_sampling',
 label: 'CNS Colored Noise Sampling',
 group: 'inference',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'cns_sampling',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Primitive/request contract exists, but sampler runtime is still gated.',
 },
 {
 id: 'smc_cfg',
 label: 'SMC-CFG',
 group: 'inference',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'smc_cfg',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: '推理侧功能，不是训练方法开关。',
 },
 {
 id: 'spectrum_probe',
 label: 'Spectrum Probe',
 group: 'inference',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'spectrum_probe',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Real-GPU block-level A/B verified: probe+seam real skip now wired via the unified cache seam (anima_native_dit._run_blocks). 20-step/32-latent: mean 1.59x step speedup (8 of 20 steps extrapolated ~3ms vs ~90ms), median 1.06x, +83MB cache VRAM, latent drift MSE 0.0017 (max 0.19). Generation-side accel, not training core;。 default path, user via UI. Promote as finished-product fast path, not a preview default (drift may mislead preview judgement).',
 },
 {
 id: 'smoothcache_probe',
 label: 'SmoothCache Probe',
 group: 'inference',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'smoothcache_probe',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Real-GPU block-level A/B verified: probe+seam real reuse now wired via the unified cache seam. Error-guided (threshold 0.08), so data-adaptive: on synthetic random latents it stayed conservative (no reuse triggered -> 1.02x, MSE 0.0, +27MB), real correlated latents expected to trigger more reuse. Generation-side accel, not training core;。 default path, user via UI.',
 },
 {
 id: 'tgate_probe',
 label: 'T-GATE Probe',
 group: 'inference',
 source: 'frontier',
 routeId: null,
 guideEntryKey: 'tgate_probe',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Observe-only attention-skip telemetry; no output-changing skip path.',
 },
 {
 id: 'easycontrol_v2',
 label: 'EasyControl v2 / Colorization',
 group: 'control',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'easycontrol_v2_enabled',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'easycontrol_v2_anima_patch.py + colorize_cond_cache.py + anima_colorize_inference.py',
 reason: 'Full colorize pipeline wired. Two-stream extended-attention patch (easycontrol_v2_anima_patch.py): no cond tokens -> original block forward (default path); zero-init LoRA + negative b_cond is near-identity at init. Training-step consumption (#184) installs the adapter, feeds the per-step condition, and saves easycontrol_v2.* with the LoRA. The colorize keystone (colorize_cond_cache.py) VAE-encodes line-art/grayscale control images into the per-target cond-latent sidecars the contract names, and AnimaCachedDataset now loads them so cache-first training consumes a REAL control condition (not the derived-from-target fallback). Real-machine validated on Anima weights + data: cond sidecars produced via the real Qwen-Image VAE, condition source = sidecar, adapter trains (253 easycontrol_v2.* keys), loss healthy. The INFERENCE mirror is wired too (anima_colorize_inference.py): load the trained adapter, encode a control image into the training-identical cond latents, and condition every DiT forward via colorize_render_scope (no control image -> bitwise-default path t2i; gate forced shut regresses to control-OFF). Real-machine render validated with a 360-step converged adapter: condition warm-up (skip the high-noise early steps, ratio 0.6 default) removes the early-trajectory damage and renders a real colored image. Smokes: anima patch 5/5 + consumption 4/4 + colorize_cond_cache 14/14 + colorize inference 7/7. Default behavior unchanged; aesthetic/identity quality and runtime activation remains gated.',
 },
 {
 id: 'step_expert_routing',
 label: 'Step Expert Routing',
 group: 'adapter',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'step_expert_routing',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'adapter_research_reserve_seam.py',
 reason: 'Real step-routed adapter wired (adapter_research_reserve_seam.py, method=step_expert): zero-init up-proj is exact identity at init, a ContextVar drives per-step routing, and remove restores the originals. method=none is default path. Validation 5/5 + 13 unit tests. Request/config adapter and checkpoint route stay gated; Runtime activation remains gated.',
 },
 {
 id: 'chimera_hydra',
 label: 'ChimeraHydra',
 group: 'adapter',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'chimera_hydra_enabled',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'adapter_research_reserve_seam.py',
 reason: 'Real ChimeraHydra adapter wired (adapter_research_reserve_seam.py, method=chimera_hydra): zero-init identity at init, diverges once trained, remove restores. Default (method=none) is default path and does not mutate current HydraLoRA behavior. Validation 5/5 + 13 unit tests. Runtime activation remains gated.',
 },
 {
 id: 'soft_tokens',
 label: 'Soft Tokens',
 group: 'adapter',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'soft_tokens_enabled',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'adapter_research_reserve_seam.py',
 reason: 'Real soft-token prepend wired (adapter_research_reserve_seam.apply_soft_tokens_reserve): bank None / disabled is default path, enabled prepends learnable tokens that carry gradient. Archived AGSM/dispersive modes stay blocked. Validation 5/5 + 13 unit tests. Runtime activation remains gated.',
 },
 {
 id: 'modulation_guidance',
 label: 'Modulation Guidance',
 group: 'adapter',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'modulation_guidance',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'modulation_guidance_reserve_seam.py',
 reason: 'Full pooled-text route wired (modulation_guidance_reserve_seam.py): a zero-init PooledTextModulationProjector adds prompt-conditioned shift/scale deltas to AdaLN (gate untouched), so method=none or no published pooled text is default path; the dedicated distill loss is off==base / on adds a real backprop term; base model init (llm_adapter/timestep_embed/adaln_modulation) is never mutated. The existing constant-bias adaln_guidance stays the separate partial route. Validation 8/8 + 15 unit tests + real-weights probe (85 sites, projector trains 0→0.107, distill 0.062→0.0013, default path/remove bitwise, faithful intact). Runtime activation remains gated.',
 },
 {
 id: 'dp_dmd_turbo',
 label: 'DP-DMD / Turbo',
 group: 'distillation',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'dp_dmd_turbo',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'dp_dmd_spd_reserve_seam.py',
 reason: 'Real DP-DMD/Turbo loss composition wired (dp_dmd_spd_reserve_seam.compose_dp_dmd_turbo_loss): disabled returns the base loss unchanged, enabled adds consistency/diversity/fake-critic terms that backprop. Validation 6/6 + 8 unit tests. Trainer wiring and quality A/B stay gated; Runtime activation remains gated.',
 },
 {
 id: 'spd_inference',
 label: 'SPD Inference',
 group: 'inference',
 source: 'anima-1.8.1',
 routeId: null,
 guideEntryKey: 'spd_inference',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'dp_dmd_spd_reserve_seam.py',
 reason: 'Real SPD multi-resolution denoise wired (dp_dmd_spd_reserve_seam.run_spd_multiresolution_denoise): disabled (and a unit-scale config) is bitwise-identical to the base-res loop, multi-resolution changes the trajectory and always returns base-res latents. Validation 6/6 + 8 unit tests. Sampler-loop activation stays gated; Runtime activation remains gated.',
 },
 {
 id: 'pid_decoder_backend',
 label: 'PiD Native Decoder',
 group: 'decoder',
 source: 'pid-main',
 routeId: null,
 guideEntryKey: 'pid_decoder_backend',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reserveSeamWired: true,
 reserveSeamModule: 'pid_decode_reserve_seam.py',
 reason: 'Real PiD decode-backend wired (pid_decode_reserve_seam.decode_with_pid_reserve): decode_backend defaults to VAE and allow_pid defaults to false, so the default path is bitwise-identical to the VAE decode. Even opted in, PiD runs only with a user-supplied local checkpoint, otherwise it honestly falls back to VAE and reports pid_blocked; it never downloads or bundles weights (NVIDIA NSCLv1 license is the user responsibility). Validation 5/5 + 5 unit tests. Preview/generation/postprocess routes stay unregistered; Runtime activation remains gated.',
 },
 {
 id: 'adapter_target_policy',
 label: 'Adapter Target Policy (gradient-selected)',
 group: 'adapter',
 source: 'frontier',
 routeId: null,
 guideEntryKey: 'adapter_target_policy',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Real-GPU 40-step A/B verified: gradient_selected top_k=2 trims 450->29 LoRA layers (-97.7% params), 0.35x step time, -340MB VRAM, +0.028 final loss. Runtime activation remains gated.',
 },
 {
 id: 'fg_lora_rank_policy',
 label: 'FG-LoRA Per-Layer Rank Policy',
 group: 'adapter',
 source: 'frontier',
 routeId: null,
 guideEntryKey: 'fg_lora_rank_policy',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Unified 3-mode per-layer rank selector wired。 (fg_lora_rank_policy): uniform = default path with legacy injection; coupled_prune reuses the adapter_target_policy layer-pruning engine (saves VRAM, drops minor layers); orthogonal_redistribute keeps ALL target layers and only reallocates per-layer rank by a depth profile (center_peak/ascending/descending/flat, optional budget conservation). The operator picks the direction; lulynx ships both as。 reserves. Reuses the LoRAInjector rank-map seam via a 1-line full-path-first rank lookup (true per-block rank, backward compatible). Validation 11/11 + 15 unit tests + adapter_target regression 18/18 (bitwise no-change). Default uniform = default path; Runtime activation remains gated.',
 },
 {
 id: 'tlora',
 label: 'T-LoRA Timestep Rank Schedule',
 group: 'adapter',
 source: 'frontier',
 routeId: null,
 guideEntryKey: 'tlora',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: false,
 runtimeActivationEnabled: false,
 trainingLaunchAllowed: false,
 visibleTrainingToggleAllowed: false,
 reason: 'Real-GPU 40-step A/B verified: linear/geometric timestep rank schedule saves ~62MB VRAM, 0.84-0.93x step time, -0.009 final loss (no regression). Runtime activation remains gated.',
 },
 {
 id: 'dit_blockskip',
 label: 'DiT Block-Skip Reducer',
 group: 'compute',
 source: 'frontier',
 routeId: null,
 guideEntryKey: 'dit_blockskip',
 backendContractReady: true,
 smokeEvidence: true,
 requestFieldsEmitted: true,
 runtimeActivationEnabled: true,
 trainingLaunchAllowed: true,
 visibleTrainingToggleAllowed: true,
 reason: 'BlockSkip 已接入训练配置链路与 live _run_blocks reducer seam：前端可发 dit_compute_reducer_strategy=blockskip，后端默认 none 保持 default path，启用后按固定计划跳过部分 DiT block 计算。保留真实质量/损失 A/B 作为算子级运营验证，不再卡住本地训练接线。',
 },
];

export const ANIMA_METHOD_READINESS = Object.freeze(entries.map((entry) => Object.freeze({ .entry })));

export function listAnimaMethodReadiness() {
 return ANIMA_METHOD_READINESS;
}

export function getAnimaMethodReadiness(id) {
 return ANIMA_METHOD_READINESS.find((entry) => entry.id === id) || null;
}

export function getVisibleTrainingToggleIds() {
 return ANIMA_METHOD_READINESS
 .filter((entry) => entry.visibleTrainingToggleAllowed)
 .map((entry) => entry.id);
}

export function getGuideOnlyMethodIds() {
 return ANIMA_METHOD_READINESS
 .filter((entry) => !entry.visibleTrainingToggleAllowed && entry.guideEntryKey)
 .map((entry) => entry.id);
}

// Reserves whose real runtime seam is wired (default-off, opt-in only). These are
// surfaced as guide entries describing a usable opt-in path, but must NEVER expose
// a launchable training toggle until an operator signs the runtime-activation gate.
export function getWiredReserveMethodIds() {
 return ANIMA_METHOD_READINESS
 .filter((entry) => entry.reserveSeamWired && !entry.visibleTrainingToggleAllowed)
 .map((entry) => entry.id);
}

export function shouldExposeAsTrainingToggle(id) {
 return Boolean(getAnimaMethodReadiness(id)?.visibleTrainingToggleAllowed);
}
