// 全局常量集中管理：状态键、UI 配置常量、字段集合等
// 这些常量在 main.js 与未来拆出的 actions/renderers 中都会用到，
// 抽取到这里是为了让 main.js 的顶部装配代码更清爽，并避免循环依赖。

import { UI_TABS } from '../trainingTypeRegistry.js';

export const TOPBAR_TABS = UI_TABS.map((tab) => tab.key);

// 用户切换这些字段时，需要联动重新渲染整个 config 视图（visibleWhen 依赖）。
// 任何会改变其他字段可见性的字段都应在这里登记。
export const CONDITIONAL_KEYS = new Set([
  'training_intent',
  'v_parameterization',
  'save_state',
  'network_module',
  'lycoris_algo',
  'lr_scheduler',
  'optimizer_type',
  'optimizer_backend',
  'advanced_optimizer_strategy',
  'enable_preview',
  'preview_device',
  'ema_enabled',
  'safeguard_enabled',
  'wavelet_loss_enabled',
  'negative_semantic_regularization_enabled',
  // frontier parent toggles — missing here makes child fields stay hidden until
  // an unrelated CONDITIONAL_KEYS field is flipped (user-visible "form only
  // appears after enabling something else" bug).
  'progressive_training_enabled',
  'adaptive_training_enabled',
  'adaptive_sample_mining_enabled',
  'multi_aspect_guidance_enabled',
  'fera_enabled',
  'fim_scan_enabled',
  'forgetting_probe_enabled',
  'grad_cosine_enabled',
  'flexrank_lora_enabled',
  'fractional_grad_damping_enabled',
  'smart_rank_enabled',
  'torch_compile',
  'enable_base_weight',
  'log_with',
  'lora_type',
  'dit_compute_reducer_strategy',
  'enable_distributed_training',
  'sync_use_password_auth',
  'lulynx_experimental_core_enabled',
  'lulynx_resource_manager_enabled',
  'lulynx_block_weight_enabled',
  'lulynx_smart_rank_enabled',
  'lulynx_lisa_enabled',
  'lulynx_pcgrad_enabled',
  'hutchinson_auto_freeze',
  'lulynx_geometric_lock',
  'lulynx_ghost_replay',
  'lulynx_pause_enabled',
  'lulynx_prodigy_guard_enabled',
  'lulynx_advanced_stats_enabled',
  'enable_block_weights',
  'sdxl_low_vram_optimization',
  'sdxl_low_vram_fixed_block_swap',
  'sdxl_unet_backend',
  'cuda_cache_release_strategy',
  'lulynx_precision_swap_enabled',
  'enable_mixed_resolution_training',
  'adapter_type',
  'bucket_selection_mode',
  'peak_vram_control_enabled',
  'peak_vram_startup_guard_enabled',
  'peak_vram_micro_batch_enabled',
  'peak_vram_diagnostics_enabled',
  'peak_vram_auto_protection_enabled',
  'experimental_attention_profile_enabled',
  'experimental_attention_profile_backend',
  'performance_expert_mode',
  'acceleration_profile',
  'cross_attn_fused_kv',
  'anima_fused_qkv',
  'fused_projection_memory_mode',
  'image_decode_backend',
  'cached_collate_mode',
  'data_transfer_profile_enabled',
  'block_swap_strategy',
  'flow_model',
  'flow_timestep_distribution',
  'flow_uniform_shift',
  'contrastive_flow_matching',
  'pissa_init',
  'dora_wd',
  'adapter_mask_pruning_enabled',
  'bypass_mode',
  'enable_debug_options',
  'caption_tag_dropout_target_mode',
  'train_length_mode',
  'shuffle_caption',
  'shuffle_caption_tags_only',
  'cache_text_encoder_outputs',
  'cache_latents',
  'cache_latents_to_disk',
  'network_train_unet_only',
  'network_train_text_encoder_only',
  'full_fp16',
  'full_bf16',
  'cache_text_encoder_outputs_to_disk',
  'caption_dropout_rate',
  'caption_tag_dropout_rate',
  'caption_dropout_every_n_epochs',
  'caption_source_mix_enabled',
  'token_warmup_step',
  'noise_offset',
  'multires_noise_iterations',
  'vram_swap_to_ram',
  'vram_auto_enhance_enabled',
  'enhanced_protection_mode',
  'vram_smart_sensing_baseline_steps',
  'vram_smart_sensing_slowdown_ratio',
  'vram_smart_sensing_delta_cache_enabled',
  'anima_block_residency',
  'anima_block_prefetch',
  'newbie_block_residency',
  'newbie_block_prefetch',
  'pcie_transfer_format',
  'sparse_swap_enabled',
  'pcie_delta_cache_enabled',
  'pcie_delta_cache_mode',
  'pcie_delta_cache_budget_mb',
  'vortex_enabled',
  'vortex_mode',
  'vortex_low_vram_protection_enabled',
  'vortex_low_vram_protection_mode',
  'swap_granularity',
  'module_offload_enabled',
  'gradient_checkpointing',
  'checkpoint_policy',
  'cpu_offload_checkpointing',
  'deepspeed',
  'safe_fallback',
  'newbie_safe_fallback',
  'timestep_sampling_mode',
  'timestep_sampling',
  'anima_weighting_scheme',
]);

// 这些字段在配置面板中折叠展示，仅在被启用时才显示完整输入。
export const COLLAPSIBLE_FIELD_KEYS = new Set([
  'reg_data_dir',
  'prior_loss_weight',
]);

// localStorage 键名（与 storage.js 配合使用）
export const DRAFT_STORAGE_KEY = 'sd-rescripts:ui:sdxl-draft';
export const DRAFT_BACKUP_STORAGE_KEY = 'sd-rescripts:ui:sdxl-draft-backup';
export const DELETED_TASK_IDS_STORAGE_KEY = 'sd-rescripts:task-history:deleted-ids';
