// 轻量级 TOML 序列化 / 反序列化（仅覆盖训练配置的平铺结构）。
// 训练 .toml 文件不含嵌套 [[section]]，所以只需一个避免模仿完整 TOML 语法的简易实现。

function _tomlValue(v) {
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) {
    // TOML 内联数组：[ "a", "b" ]
    return '[ ' + v.map(item => {
      if (typeof item === 'string') return '"' + item.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
      return String(item);
    }).join(', ') + ' ]';
  }
  if (typeof v === 'string') {
    return '"' + v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
  }
  return String(v);
}

/**
 * 将平铺配置对象序列化为 TOML 文本。
 * undefined / null 字段会被跳过。
 */
export function configToToml(config) {
  const lines = ['# Generated by LoRA ReScripts UI', '# ' + new Date().toISOString(), ''];
  for (const [key, val] of Object.entries(config)) {
    if (val === undefined || val === null) continue;
    lines.push(key + ' = ' + _tomlValue(val));
  }
  return lines.join('\n') + '\n';
}

/**
 * 解析简易 TOML（平铺结构）。
 * 支持：bool / number / string / 字符串数组（含多行）。
 * 忿略 [section] 头、不支持嵌套表。
 */
export function parseSimpleToml(text) {
  const result = {};
  // 预处理：将多行数组合并为单行，以便逐行解析
  const rawLines = text.split(/\r?\n/);
  const mergedLines = [];
  for (let i = 0; i < rawLines.length; i++) {
    let line = rawLines[i];
    // 检测行尾有未闭合的 [ （简单启发式：= [ 但同行没有 ]）
    if (/=\s*\[/.test(line) && !line.includes(']')) {
      while (i + 1 < rawLines.length && !rawLines[i].includes(']')) {
        i++;
        line += ' ' + rawLines[i].trim();
      }
    }
    mergedLines.push(line);
  }
  for (const raw of mergedLines) {
    // 剔除注释，但仅在字符串外的 # 才算
    const commentIdx = raw.indexOf('#');
    const quoteBeforeComment = commentIdx >= 0 ? (raw.slice(0, commentIdx).split('"').length - 1) % 2 : 0;
    const line = (quoteBeforeComment ? raw : (commentIdx >= 0 ? raw.slice(0, commentIdx) : raw)).trim();
    if (!line || line.startsWith('[')) continue; // 跳过空行、注释、section 头
    const eqIdx = line.indexOf('=');
    if (eqIdx < 1) continue;
    const key = line.slice(0, eqIdx).trim();
    let val = line.slice(eqIdx + 1).trim();
    // boolean
    if (val === 'true') { result[key] = true; continue; }
    if (val === 'false') { result[key] = false; continue; }
    // array
    if (val.startsWith('[')) {
      // 简易内联数组解析器
      const inner = val.slice(1, val.lastIndexOf(']')).trim();
      if (!inner) { result[key] = []; continue; }
      const items = [];
      // 匹配引号字符串或逗号间的裸值
      const re = /"((?:[^"\\]|\\.)*)"|([^,"\s]+)/g;
      let m;
      while ((m = re.exec(inner)) !== null) {
        if (m[1] !== undefined) items.push(m[1].replace(/\\\\/g, '\\').replace(/\\"/g, '"'));
        else if (m[2] !== undefined) {
          const n = Number(m[2]);
          items.push(Number.isNaN(n) ? m[2] : n);
        }
      }
      result[key] = items; continue;
    }
    // 引号字符串
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      result[key] = val.slice(1, -1).replace(/\\\\/g, '\\').replace(/\\"/g, '"').replace(/\\n/g, '\n');
      continue;
    }
    // 数字
    const num = Number(val);
    if (!Number.isNaN(num) && val !== '') { result[key] = num; continue; }
    // 其他裸字符串
    result[key] = val;
  }
  return result;
}
