// 轻量级 TOML 序列化 / 反序列化。
// 这里不追求完整 TOML 规范，只覆盖训练配置导入导出需要的：
// - 基础标量
// - 内联数组
// - 基础 [section] 嵌套对象

function _tomlValue(v) {
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) {
    // TOML 内联数组：[ "a", "b" ]
    return '[ ' + v.map(item => {
      if (typeof item === 'string') return '"' + item.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
      return String(item);
    }).join(', ') + ' ]';
  }
  if (typeof v === 'string') {
    return '"' + v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
  }
  return String(v);
}

/**
 * 将平铺配置对象序列化为 TOML 文本。
 * undefined / null 字段会被跳过。
 */
export function configToToml(config) {
  const lines = ['# Generated by LoRA ReScripts UI', '# ' + new Date().toISOString(), ''];
  for (const [key, val] of Object.entries(config)) {
    if (val === undefined || val === null) continue;
    lines.push(key + ' = ' + _tomlValue(val));
  }
  return lines.join('\n') + '\n';
}

function stripComment(raw) {
  let inQuote = false;
  let quoteChar = '';
  let escaped = false;
  let out = '';
  for (const ch of String(raw || '')) {
    if (inQuote) {
      out += ch;
      if (escaped) {
        escaped = false;
      } else if (ch === '\\') {
        escaped = true;
      } else if (ch === quoteChar) {
        inQuote = false;
      }
      continue;
    }
    if (ch === '"' || ch === "'") {
      inQuote = true;
      quoteChar = ch;
      out += ch;
      continue;
    }
    if (ch === '#') {
      break;
    }
    out += ch;
  }
  return out.trim();
}

function parseTomlScalar(raw) {
  const val = String(raw ?? '').trim();
  if (val === 'true') return true;
  if (val === 'false') return false;
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
    return val.slice(1, -1).replace(/\\\\/g, '\\').replace(/\\"/g, '"').replace(/\\n/g, '\n');
  }
  const num = Number(val);
  if (!Number.isNaN(num) && val !== '') return num;
  return val;
}

function parseTomlArray(raw) {
  const inner = raw.slice(1, raw.lastIndexOf(']')).trim();
  if (!inner) return [];
  const items = [];
  const re = /"((?:[^"\\]|\\.)*)"|'((?:[^'\\]|\\.)*)'|([^,"\s][^,]*)/g;
  let m;
  while ((m = re.exec(inner)) !== null) {
    if (m[1] !== undefined) {
      items.push(m[1].replace(/\\\\/g, '\\').replace(/\\"/g, '"'));
    } else if (m[2] !== undefined) {
      items.push(m[2].replace(/\\\\/g, '\\').replace(/\\'/g, "'"));
    } else if (m[3] !== undefined) {
      items.push(parseTomlScalar(m[3].trim()));
    }
  }
  return items;
}

function ensureTomlSection(root, path) {
  let current = root;
  for (const key of path) {
    if (!current[key] || typeof current[key] !== 'object' || Array.isArray(current[key])) {
      current[key] = {};
    }
    current = current[key];
  }
  return current;
}

/**
 * 解析简易 TOML。
 * 支持：bool / number / string / 字符串数组（含多行）/ [section]。
 */
export function parseSimpleToml(text) {
  const result = {};
  let currentSection = [];
  // 预处理：将多行数组合并为单行，以便逐行解析
  const rawLines = text.split(/\r?\n/);
  const mergedLines = [];
  for (let i = 0; i < rawLines.length; i++) {
    let line = rawLines[i];
    // 检测行尾有未闭合的 [ （简单启发式：= [ 但同行没有 ]）
    if (/=\s*\[/.test(line) && !line.includes(']')) {
      while (i + 1 < rawLines.length && !rawLines[i].includes(']')) {
        i++;
        line += ' ' + rawLines[i].trim();
      }
    }
    mergedLines.push(line);
  }
  for (const raw of mergedLines) {
    const line = stripComment(raw);
    if (!line) continue;
    if (line.startsWith('[') && line.endsWith(']')) {
      const section = line.slice(1, -1).trim();
      currentSection = section
        ? section.split('.').map((part) => part.trim()).filter(Boolean)
        : [];
      ensureTomlSection(result, currentSection);
      continue;
    }
    const eqIdx = line.indexOf('=');
    if (eqIdx < 1) continue;
    const key = line.slice(0, eqIdx).trim();
    let val = line.slice(eqIdx + 1).trim();
    const target = ensureTomlSection(result, currentSection);
    // boolean
    if (val === 'true') { target[key] = true; continue; }
    if (val === 'false') { target[key] = false; continue; }
    // array
    if (val.startsWith('[')) {
      target[key] = parseTomlArray(val);
      continue;
    }
    // 引号字符串
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      target[key] = val.slice(1, -1).replace(/\\\\/g, '\\').replace(/\\"/g, '"').replace(/\\n/g, '\n');
      continue;
    }
    // 数字
    const num = Number(val);
    if (!Number.isNaN(num) && val !== '') { target[key] = num; continue; }
    // 其他裸字符串
    target[key] = val;
  }
  return result;
}
